apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartops-frontend
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: smartops-frontend
  template:
    metadata:
      labels:
        app: smartops-frontend
    spec:
      containers:
        - name: smartops-frontend
          image: europe-west1-docker.pkg.dev/smartops-hub-project/smartops-hub-project-dev/smartops-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://146.148.27.168"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
