apiVersion: v1
kind: ConfigMap
metadata:
  name: smartops-config
  namespace: staging
data:
  SPRING_APPLICATION_NAME: smartops-hub-staging
  SPRING_DATASOURCE_URL: jdbc:postgresql://35.205.232.148:5432/smartops
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  ANTHROPIC_API_ENABLED: "true"
  ANTHROPIC_MODEL: claude-haiku-4-5-20251001
  AI_ANALYSIS_INTERVAL: "3600000"
